import type { DeployedContract } from '../../shared/types'
import {
  fetchCatalog as _fetchCatalog,
  deployContract as _deployContract,
} from './backend'

export type { Manifest, DeployResult } from '../../shared/types'

/** Fetch the deployable + connectable contract catalog. */
export function fetchCatalog() {
  return _fetchCatalog()
}

/** Deploy a configurable contract to testnet with the given config.
 *  When deployerSecret is provided the user's wallet signs the deploy and
 *  becomes the contract owner — the {{deployer}} sentinel resolves to it. */
export function deployContract(
  projectId: string,
  manifestId: string,
  config: Record<string, unknown>,
  deployerSecret?: string,
) {
  return _deployContract(projectId, manifestId, config, deployerSecret)
}

/**
 * Generate `src/contracts.ts` for the user's app — a typed registry of the
 * contract IDs deployed for this project, so the generated dApp can call them.
 */
export function buildContractsFile(contracts: DeployedContract[]): string {
  const entries = contracts
    .map(
      (c) => `  ${JSON.stringify(c.manifestId)}: {
    name: ${JSON.stringify(c.name)},
    category: ${JSON.stringify(c.category)},
    contractId: ${JSON.stringify(c.contractId)},
    owner: ${JSON.stringify((c.config?.owner as string) ?? c.deployer ?? '')},
    explorerUrl: ${JSON.stringify(c.explorerUrl)},
  },`,
    )
    .join('\n')

  // A funded account that exists on-chain, used only as the source for
  // read-only simulations (so reads work before a wallet is connected).
  const viewSource = contracts.find((c) => c.deployer)?.deployer ?? ''

  return `// Auto-generated by xlmcode. Do not edit by hand.
// Contracts deployed to Stellar testnet for this project.
export const NETWORK = 'testnet' as const
export const RPC_URL = 'https://soroban-testnet.stellar.org' as const
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015' as const

// Funded source for read-only contract simulations (no signing).
export const VIEW_SOURCE = ${JSON.stringify(viewSource)}

export const CONTRACTS = {
${entries}
} as const

export type ContractKey = keyof typeof CONTRACTS
`
}

/** Path of the injected registry inside the generated app's file tree. */
export const CONTRACTS_FILE = '/contracts.ts'
